services:
  backend:
    build: ./backend
    container_name: bitwise-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - python-backend
    restart: unless-stopped

  python-backend:
    build: ./python-backend
    container_name: bitwise-python
    ports:
      - "8501:8501"
    env_file:
      - ./python-backend/.env
    restart: unless-stopped
